// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJUSuB-IxJMM4JUrrLGQyCIR4AU--B48',
    appId: '1:486508979506:web:74b373a18769596b62232b',
    messagingSenderId: '486508979506',
    projectId: 'cbcapp-fd2b5',
    authDomain: 'cbcapp-fd2b5.firebaseapp.com',
    storageBucket: 'cbcapp-fd2b5.appspot.com',
    measurementId: 'G-ZCX5ZSJTK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJ4XeORj8oc5ZWR3Z2C8-ug2uUThb_ak',
    appId: '1:486508979506:android:a779c03f4a2df13762232b',
    messagingSenderId: '486508979506',
    projectId: 'cbcapp-fd2b5',
    storageBucket: 'cbcapp-fd2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZ_RCjtJ1pvw5HRgVO8r8p-rq12-52o8',
    appId: '1:486508979506:ios:c67f4d52b0c68d0d62232b',
    messagingSenderId: '486508979506',
    projectId: 'cbcapp-fd2b5',
    storageBucket: 'cbcapp-fd2b5.appspot.com',
    iosBundleId: 'com.seco.cbc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZ_RCjtJ1pvw5HRgVO8r8p-rq12-52o8',
    appId: '1:486508979506:ios:20ec3c47985d889462232b',
    messagingSenderId: '486508979506',
    projectId: 'cbcapp-fd2b5',
    storageBucket: 'cbcapp-fd2b5.appspot.com',
    iosBundleId: 'com.example.uiEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALJUSuB-IxJMM4JUrrLGQyCIR4AU--B48',
    appId: '1:486508979506:web:b416e3bb265f874862232b',
    messagingSenderId: '486508979506',
    projectId: 'cbcapp-fd2b5',
    authDomain: 'cbcapp-fd2b5.firebaseapp.com',
    storageBucket: 'cbcapp-fd2b5.appspot.com',
    measurementId: 'G-FP6Z3WRCTC',
  );
}
